"use strict";

exports.__esModule = true;
exports.crAxisCl = exports.CL_WRAPPER = exports.CL_TOOLTIP_WRAPPER = exports.CL_TOOLTIP_LABEL = exports.CL_TOOLTIP_ITEM_VALUE = exports.CL_TOOLTIP_ITEM_UNIT = exports.CL_TOOLTIP_ITEM_SEPARATOR = exports.CL_TOOLTIP_ITEM_NAME = exports.CL_TOOLTIP_ITEM_LIST = exports.CL_TOOLTIP_ITEM = exports.CL_TEXT = exports.CL_STRIPES_VERTICAL = exports.CL_STRIPES_HORIZONTAL = exports.CL_RESTANGLE = exports.CL_RESPONSIVE_CONTAINER = exports.CL_RECHARTS_SURFACE = exports.CL_RECHARTS_LAYER = exports.CL_LINE_DOTS = exports.CL_LINE_DOT = exports.CL_LINE_CURVE = exports.CL_LINE = exports.CL_LEGEND_ITEM_TEXT = exports.CL_LEGEND_ITEM = exports.CL_LEGEND_ICON = exports.CL_LABEL = exports.CL_GRID_VERTICAL = exports.CL_GRID_HORIZONTAL = exports.CL_DOT = exports.CL_DF_LEGEND = exports.CL_DEFAULT_TOOLTIP = exports.CL_CURVE = exports.CL_CARTESIAN_GRID = exports.CL_BG = exports.CL_BAR_RECTANGLES = exports.CL_BAR_RECTANGLE = exports.CL_BAR_BACKGROUND_RECTANGLE = exports.CL_BAR = exports.CL_AXIS_TICK_VALUE = exports.CL_AXIS_TICK_LINE = exports.CL_AXIS_TICKS = exports.CL_AXIS_TICK = exports.CL_AXIS_LINE = exports.CL_AXIS = void 0;
const CHART_PREFIX = 'recharts';
const CHART_CARTESIAN = CHART_PREFIX + "-cartesian";
const CL_WRAPPER = exports.CL_WRAPPER = CHART_PREFIX + "-wrapper";
const crAxisCl = axisType => CHART_PREFIX + "-" + axisType + " " + axisType;
exports.crAxisCl = crAxisCl;
const CL_BAR = exports.CL_BAR = CHART_PREFIX + "-bar";
const CL_BAR_RECTANGLE = exports.CL_BAR_RECTANGLE = CL_BAR + "-rectangle";
const CL_BAR_RECTANGLES = exports.CL_BAR_RECTANGLES = CL_BAR_RECTANGLE + "s";
const CL_BAR_BACKGROUND_RECTANGLE = exports.CL_BAR_BACKGROUND_RECTANGLE = CL_BAR + "-background-rectangle";
const CL_LINE = exports.CL_LINE = CHART_PREFIX + "-line";
const CL_LINE_DOT = exports.CL_LINE_DOT = CL_LINE + "-dot";
const CL_LINE_DOTS = exports.CL_LINE_DOTS = CL_LINE_DOT + "s";
const CL_LINE_CURVE = exports.CL_LINE_CURVE = CL_LINE + "-curve";
const CL_AXIS = exports.CL_AXIS = CHART_CARTESIAN + "-axis";
const CL_AXIS_LINE = exports.CL_AXIS_LINE = CL_AXIS + "-line";
const CL_AXIS_TICK = exports.CL_AXIS_TICK = CL_AXIS + "-tick";
const CL_AXIS_TICKS = exports.CL_AXIS_TICKS = CL_AXIS_TICK + "s";
const CL_AXIS_TICK_LINE = exports.CL_AXIS_TICK_LINE = CL_AXIS_TICK + "-line";
const CL_AXIS_TICK_VALUE = exports.CL_AXIS_TICK_VALUE = CL_AXIS_TICK + "-value";
const CL_CARTESIAN_GRID = exports.CL_CARTESIAN_GRID = CHART_CARTESIAN + "-grid";
const CL_GRID_HORIZONTAL = exports.CL_GRID_HORIZONTAL = CL_CARTESIAN_GRID + "-horizontal";
const CL_GRID_VERTICAL = exports.CL_GRID_VERTICAL = CL_CARTESIAN_GRID + "-vertical";
const CL_BG = exports.CL_BG = CL_CARTESIAN_GRID + "-bg";
const CHART_CARTESIAN_GRID_STRIPES = CL_CARTESIAN_GRID + "stripes";
const CL_STRIPES_HORIZONTAL = exports.CL_STRIPES_HORIZONTAL = CHART_CARTESIAN_GRID_STRIPES + "-horizontal";
const CL_STRIPES_VERTICAL = exports.CL_STRIPES_VERTICAL = CHART_CARTESIAN_GRID_STRIPES + "-vertical";
const LEGEND = 'legend';
const CHART_LEGEND = CHART_PREFIX + "-" + LEGEND;
const CL_LEGEND_ICON = exports.CL_LEGEND_ICON = CHART_LEGEND + "-icon";
const CL_LEGEND_ITEM = exports.CL_LEGEND_ITEM = CHART_LEGEND + "-item";
const CL_LEGEND_ITEM_TEXT = exports.CL_LEGEND_ITEM_TEXT = CL_LEGEND_ITEM + "-text";
const CL_DF_LEGEND = exports.CL_DF_LEGEND = CHART_PREFIX + "-default-" + LEGEND;
const CHART_TOOLTIP = CHART_PREFIX + "-tooltip";
const CL_TOOLTIP_ITEM = exports.CL_TOOLTIP_ITEM = CHART_TOOLTIP + "-item";
const CL_TOOLTIP_ITEM_NAME = exports.CL_TOOLTIP_ITEM_NAME = CL_TOOLTIP_ITEM + "-name";
const CL_TOOLTIP_ITEM_SEPARATOR = exports.CL_TOOLTIP_ITEM_SEPARATOR = CL_TOOLTIP_ITEM + "-separator";
const CL_TOOLTIP_ITEM_VALUE = exports.CL_TOOLTIP_ITEM_VALUE = CL_TOOLTIP_ITEM + "-value";
const CL_TOOLTIP_ITEM_UNIT = exports.CL_TOOLTIP_ITEM_UNIT = CL_TOOLTIP_ITEM + "-unit";
const CL_TOOLTIP_ITEM_LIST = exports.CL_TOOLTIP_ITEM_LIST = CL_TOOLTIP_ITEM + "-list";
const CL_DEFAULT_TOOLTIP = exports.CL_DEFAULT_TOOLTIP = CHART_PREFIX + "-default-tooltip";
const CL_TOOLTIP_LABEL = exports.CL_TOOLTIP_LABEL = CHART_TOOLTIP + "-label";
const CL_TOOLTIP_WRAPPER = exports.CL_TOOLTIP_WRAPPER = CHART_PREFIX + "-tooltip-wrapper";
const CL_LABEL = exports.CL_LABEL = CHART_PREFIX + "-label";
const CL_RESPONSIVE_CONTAINER = exports.CL_RESPONSIVE_CONTAINER = CHART_PREFIX + "-responsive-container";
const CL_TEXT = exports.CL_TEXT = CHART_PREFIX + "-text";
const CL_RECHARTS_LAYER = exports.CL_RECHARTS_LAYER = CHART_PREFIX + "-layer";
const CL_RECHARTS_SURFACE = exports.CL_RECHARTS_SURFACE = CHART_PREFIX + "-surface";
const CL_CURVE = exports.CL_CURVE = CHART_PREFIX + "-curve";
const CL_DOT = exports.CL_DOT = CHART_PREFIX + "-dot";
const CL_RESTANGLE = exports.CL_RESTANGLE = CHART_PREFIX + "-rectangle";
//# sourceMappingURL=CL.js.map